### ISSUE TITLE
Umbrella 

### ISSUE THREAD

**Issue by sophiebulkin** [Mewe14/P3Platypodes#9]
Overall purpose: To create a LinkDN website for the students of Del Norte so that they can connect with one another and learn more about the campus.

Theme Section 
- [x]  4 key interactions : Feedback Page (sophie), Quiz page using API(sophie with help) , Interactions between users(Ida), contact page (arul), gpa calculator (sophie)
- [ ] Quiz Page using API - also counts as something fun for the user to do
- possible API:https://rapidapi.com/lattice-data-lattice-data-default/api/job-search4 

Individual Section 

- [ ] all of our minicabs and information for the college board should be converted and put into one file that has our names in the nav bar

Rest API
- [ ] crossover sharing of rest API will be taken care of (crystal and ida)

Deployment Section
- [x]  Ida will deploy the website according to Mr.M's requirements so that it works at Night at the Museum 
- [x] Add a how it was made button in the Nav Bar and embed our scrum board/ pieces of our code (sophie) 

SPECIFIC TASKS AND PROGRESS IS SHOWN IN INDIVIDUAL TICKETS! (EX: SOPHIES PROGRESS)
